# Generated by Django 6.0.2 on 2026-02-26 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, help_text='Primary operating region of the vendor (e.g. Java, Sumatra)', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(help_text='Unique tracking number for this delivery', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('origin_city', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('order_date', models.DateField(help_text='Date the order was placed')),
                ('scheduled_date', models.DateField(help_text='Expected delivery date agreed with vendor')),
                ('actual_delivery_date', models.DateField(blank=True, help_text='Actual date the delivery was completed (leave blank if pending)', null=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Package weight in kilograms', max_digits=8)),
                ('recipient_name', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(help_text='The vendor handling this delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='deliveries.vendor')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-order_date'],
            },
        ),
    ]
