# Generated by Django 6.0.2 on 2026-02-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of items in this delivery'),
        ),
    ]
