# Generated by Django 6.0.2 on 2026-02-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_delivery_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Number of items in this delivery'),
        ),
    ]
